# Generated by Django 6.0 on 2025-12-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatails',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdatails',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdatails',
            name='phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdatails',
            name='street',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdatails',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='userimg/'),
        ),
        migrations.AddField(
            model_name='userdatails',
            name='zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
