# Generated by Django 6.0 on 2026-01-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0002_userdatails_address_userdatails_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatails',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdatails',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdatails',
            name='phone',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdatails',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdatails',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
