# Generated by Django 6.0 on 2026-01-05 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0004_userdetails_delete_userdatails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDatails',
        ),
    ]
