# Generated by Django 6.0 on 2026-01-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0006_userdetails_delete_userdatails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
