# Generated by Django 6.0 on 2026-01-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0007_alter_userdetails_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='userimg/'),
        ),
    ]
