# Generated by Django 6.0 on 2026-01-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0002_fooditems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Breverages'), ('BRIYANI', 'Briyani')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
