# Generated by Django 6.0 on 2026-01-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0003_fooditems_catogery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='catogery',
        ),
        migrations.AddField(
            model_name='fooditems',
            name='category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Breverages'), ('BRIYANI', 'Briyani')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='foodimg',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
