# Generated by Django 6.0 on 2026-01-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0004_remove_fooditems_catogery_fooditems_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='category',
        ),
        migrations.AddField(
            model_name='fooditems',
            name='catogery',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Breverages'), ('BRIYANI', 'Briyani')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='foodimg',
            field=models.ImageField(blank=True, null=True, upload_to='foodimg/'),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
